-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.0
    hooks:
    -   id: trailing-whitespace
    -   id: autopep8-wrapper
    -   id: check-added-large-files
    -   id: debug-statements
    -   id: name-tests-test
#-   repo: https://github.com/asottile/reorder_python_imports
    #sha: v0.3.1
    #hooks:
    #-   id: reorder-python-imports
        #language_version: python3.6
